import styled from 'styled-components';
import { FaFileAlt } from 'react-icons/fa';
import { FaRegCommentAlt } from 'react-icons/fa';
import { FaStar } from 'react-icons/fa';
import { FaCode } from 'react-icons/fa';
import { FaCodeBranch } from 'react-icons/fa';
import uuid from 'react-uuid';

const Gist = ({ gist }) => {

  //Showing all the relevant meta data available in the response
  console.log(gist);

  //Converting the files into array format
  const files = Object.values(gist.files);

  //Destructuring variables from the owner property of the gist
  const {avatar_url,login} = gist.owner;

  //Destructuring variables from the gist
  const {description,created_at,updated_at} = gist;

  return(
    <GistPost key={gist.id}>
      <GistPostHeader>
        <ImgAndName>
          <ImgAndNameImg src={avatar_url} alt="This is the dummy DP"/>
          <ImgAndNameName>{login}</ImgAndNameName>
        </ImgAndName>
        <Spacing></Spacing>
        <GistResponse>
          <div> <FaCode/> {files.length} Files </div>
          <div> <FaCodeBranch/> Forks </div> 
          <div> <FaRegCommentAlt/> Comments </div> 
          <div> <FaStar/> Stars </div> 
        </GistResponse>
      </GistPostHeader>
      <GistPostTimeStamp>
        Created at: {created_at} &nbsp; &nbsp; Last Updated: {updated_at}
      </GistPostTimeStamp>
      <GistPostGeneration>
        Generated by {description ? description : 'anonymous'}
      </GistPostGeneration>
      <GistPostFiles>
        {files.map(file=><GistPostFile key={uuid()}><FaFileAlt/><span style={{'marginLeft':'5px'}}>{file.filename}</span></GistPostFile>)}
      </GistPostFiles>    
    </GistPost>
  )
}

const GistPost = styled.div`
  width:35%;
  padding-top:12px;
  padding-bottom:16px;
  border-bottom: 1px solid #d3d3d3;
  display:flex;
  flex-direction:column;
`;

const GistPostHeader = styled.div`
  height:20%;
  display:flex;
  align-items: center;
  margin-bottom: 7px;
  color:blue;
`

const ImgAndName = styled.div`
  display:flex;
  max-width:30%;
  height:100%;
  align-items:center;
`;

const ImgAndNameImg = styled.img`
  border-radius:50%;
  height:30px;
`;

const ImgAndNameName = styled.div`
    margin-left:5px;
`;

const Spacing = styled.div`
  flex:1;
`;

const GistResponse = styled.div`
  display:flex;
  justify-content:space-between;
  width:65%;
`;

const GistPostTimeStamp = styled.div`
  display:flex;
  font-size: 11px;
  font-weight: 300px;
  font-family: sans-serif;
  margin-bottom: 12px;
`;

const GistPostGeneration = styled.div`
  margin-bottom:14px;
`;

const GistPostFiles = styled.div`
  display:flex;
  margin-bottom:14px;
  font-size: 10px;
  flex-wrap: wrap;
`;

const GistPostFile = styled.div`
  color:blue;
  margin-left:14px;
  display:flex;
`;

export default Gist;
